name: Lint
on:
  pull_request: {}
jobs:
  build:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm ci

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true

      - name: Run tests
        run: npm run test

      - name: fix-lcov
        run: |
          sed -i 's|/home/runner/work/sdlc-ui/sdlc-ui|/github/workspace|g' coverage/lcov.info
          cat coverage/lcov.info

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

